---
linters:
  # see also https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errchkjson
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - govet
    - unconvert
    - revive
