---
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: ./dist/raw/*
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    signature: '${artifact}.sig'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
release:
  github:
    owner: RedeployAB
    name: tflint-ruleset-redeploy
  draft: true
snapshot:
  version_template: "{{ .Tag }}-dev"
