---
name: E2E

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  e2e:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a
        with:
          tflint_version: v0.61.0

      - name: Install plugin
        run: make install

      - name: Run E2E tests
        run: make e2e
