---
name: Code linting

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: v2.1.6

  super-linter:
    name: Lint codebase
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run linter
        uses: super-linter/super-linter/slim@7bba2eeb89d01dc9bfd93c497477a57e72c83240
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          FILTER_REGEX_EXCLUDE: "^.*/testdata/.*.tf$"
          IGNORE_GENERATED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_TERRAFORM_TFLINT: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_GIT_COMMITLINT: false

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
