---
name: Code linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter
        uses: super-linter/super-linter/slim@v7.2.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: true
          VALIDATE_TERRAFORM_TFLINT: false
          VALIDATE_TERRAFORM_TERRASCAN: false
