---
name: PR

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  title:
    name: Validate title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Keep in sync with type-enum in commitlint.config.js.
          types: |
            build
            chore
            ci
            deps
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          ignoreLabels: |
            dependencies
  labeler:
    name: Check size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: codelytv/pr-size-labeler@4e3aa0f77f348c8066513d453515316ffa01a607
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message_if_xl: ""
          files_to_ignore: |
            "README.md"
            "CHANGELOG.md"
            "go.mod"
            "go.sum"
