---
name: PR

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  title:
    name: Validate title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            ci
            docs
            feat
            fix
            refactor
            revert
            style
            test
            deps
            infra
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          ignoreLabels: |
            dependencies
  labeler:
    name: Check size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: codelytv/pr-size-labeler@4ec67706cd878fbc1c8db0a5dcd28b6bb412e85a
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message_if_xl: ""
          files_to_ignore: |
            "README.md"
            "CHANGELOG.md"
            "go.mod"
            "go.sum"
